### ISSUE TITLE
Compiler errors when trying to install gem with Ruby 1.9.x and gdal 1.11

### ISSUE THREAD

**Issue by timwaters** [zhm/gdal-ruby#4]
I get a number of compiler errors when trying to install the gem. They all seem to be related to one thing though: 
```
-Werror=format-security
```
I am using this with a new Ubuntu LTS 14 Trusty install

Using Ruby 1.9.1  (ruby 1.9.3p484 )

installed libgdal-ruby from ubuntugis-unstable repository

gdal-config --version
1.11.0

(note, on a 12.04 ubuntu + rvm 1.9.3. gem was installed - using gdal 1.10.0)

Many thanks in advance for your help!

The gem_make.out file.
```
/var/lib/gems/1.9.1/gems/gdal-0.0.5/ext/gdal-ruby/ogr/gem_make.out
/usr/bin/ruby1.9.1 extconf.rb
checking for main() in -lgdal... yes
creating Makefile

make
compiling ogr.cpp
In file included from /usr/include/gdal/cpl_progress.h:33:0,
                 from /usr/include/gdal/ogr_api.h:43,
                 from ogr.cpp:1869:
/usr/include/gdal/cpl_port.h:349:0: warning: "STRCASECMP" redefined [enabled by default]
 #    define STRCASECMP(a,b)         (strcasecmp(a,b))
 ^
In file included from /usr/include/ruby-1.9.1/ruby.h:32:0,
                 from ogr.cpp:856:
/usr/include/ruby-1.9.1/ruby/ruby.h:1466:0: note: this is the location of the previous definition
 #define STRCASECMP(s1, s2) (st_strcasecmp((s1), (s2)))
 ^
In file included from /usr/include/gdal/cpl_progress.h:33:0,
                 from /usr/include/gdal/ogr_api.h:43,
                 from ogr.cpp:1869:
/usr/include/gdal/cpl_port.h:350:0: warning: "STRNCASECMP" redefined [enabled by default]
 #    define STRNCASECMP(a,b,n)      (strncasecmp(a,b,n))
 ^
In file included from /usr/include/ruby-1.9.1/ruby.h:32:0,
                 from ogr.cpp:856:
/usr/include/ruby-1.9.1/ruby/ruby.h:1467:0: note: this is the location of the previous definition
 #define STRNCASECMP(s1, s2, n) (st_strncasecmp((s1), (s2), (n)))
 ^
ogr.cpp: In function ‘void SWIG_Ruby_define_class(swig_type_info*)’:
ogr.cpp:1517:9: warning: variable ‘klass’ set but not used [-Wunused-but-set-variable]
   VALUE klass;
         ^
ogr.cpp: In function ‘VALUE SWIG_AUX_NUM2DBL(VALUE*)’:
ogr.cpp:2245:9: warning: unused variable ‘type’ [-Wunused-variable]
   VALUE type = TYPE(obj);
         ^
ogr.cpp: In function ‘void OGRLayerShadow_each(OGRLayerShadow*)’:
ogr.cpp:2375:66: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
    while (feature = (OGRFeatureShadow*) OGR_L_GetNextFeature(self))
                                                                  ^
ogr.cpp: In function ‘VALUE _wrap_Driver_create_data_source(int, VALUE*, VALUE)’:
ogr.cpp:3339:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:3339:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:3339:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:3337:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_Driver_copy_data_source(int, VALUE*, VALUE)’:
ogr.cpp:3435:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:3435:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:3435:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:3435:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:3433:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_Driver_open(int, VALUE*, VALUE)’:
ogr.cpp:3535:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:3535:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:3535:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:3533:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_DataSource_delete_layer(int, VALUE*, VALUE)’:
ogr.cpp:4267:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_DataSource_sync_to_disk(int, VALUE*, VALUE)’:
ogr.cpp:4330:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_DataSource_create_layer(int, VALUE*, VALUE)’:
ogr.cpp:4371:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:4371:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:4371:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:4371:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:4371:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:4369:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_DataSource_copy_layer(int, VALUE*, VALUE)’:
ogr.cpp:4485:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:4485:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:4485:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:4485:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:4483:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_DataSource_execute_sql(int, VALUE*, VALUE)’:
ogr.cpp:4663:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:4663:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:4663:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:4663:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:4661:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_Layer_set_attribute_filter(int, VALUE*, VALUE)’:
ogr.cpp:5155:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_Layer_set_next_by_index(int, VALUE*, VALUE)’:
ogr.cpp:5604:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_Layer_set_feature(int, VALUE*, VALUE)’:
ogr.cpp:5680:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_Layer_create_feature(int, VALUE*, VALUE)’:
ogr.cpp:5756:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_Layer_delete_feature(int, VALUE*, VALUE)’:
ogr.cpp:5827:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_Layer_sync_to_disk(int, VALUE*, VALUE)’:
ogr.cpp:5890:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_Layer_get_feature_count(int, VALUE*, VALUE)’:
ogr.cpp:5977:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:5977:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:5975:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_Layer_get_extent(int, VALUE*, VALUE)’:
ogr.cpp:6045:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:6045:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:6091:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp:6043:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_Layer_create_field(int, VALUE*, VALUE)’:
ogr.cpp:6210:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:6210:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:6210:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:6262:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp:6208:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_Layer_delete_field(int, VALUE*, VALUE)’:
ogr.cpp:6333:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_Layer_reorder_field(int, VALUE*, VALUE)’:
ogr.cpp:6412:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_Layer_reorder_fields(int, VALUE*, VALUE)’:
ogr.cpp:6496:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_Layer_alter_field_defn(int, VALUE*, VALUE)’:
ogr.cpp:6600:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_Layer_start_transaction(int, VALUE*, VALUE)’:
ogr.cpp:6663:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_Layer_commit_transaction(int, VALUE*, VALUE)’:
ogr.cpp:6726:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_Layer_rollback_transaction(int, VALUE*, VALUE)’:
ogr.cpp:6789:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_Layer_set_ignored_fields(int, VALUE*, VALUE)’:
ogr.cpp:6972:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_new_Feature(int, VALUE*, VALUE)’:
ogr.cpp:7097:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:7095:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_Feature_set_geometry(int, VALUE*, VALUE)’:
ogr.cpp:7250:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_Feature_set_geometry_directly(int, VALUE*, VALUE)’:
ogr.cpp:7319:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_Feature_set_fid(int, VALUE*, VALUE)’:
ogr.cpp:8931:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_Feature_set_from(int, VALUE*, VALUE)’:
ogr.cpp:10285:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:10285:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:10285:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:10337:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp:10283:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_Feature_set_from_with_map(int, VALUE*, VALUE)’:
ogr.cpp:10442:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_new_FeatureDefn(int, VALUE*, VALUE)’:
ogr.cpp:10861:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:10859:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_new_FieldDefn(int, VALUE*, VALUE)’:
ogr.cpp:11639:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:11639:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:11637:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_create_geometry_from_wkb(int, VALUE*, VALUE)’:
ogr.cpp:12542:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:12542:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:12540:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_create_geometry_from_wkt(int, VALUE*, VALUE)’:
ogr.cpp:12608:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:12608:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:12606:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_build_polygon_from_edges(int, VALUE*, VALUE)’:
ogr.cpp:12794:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:12794:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:12794:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:12794:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:12792:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_approximate_arc_angles(int, VALUE*, VALUE)’:
ogr.cpp:12898:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:12898:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:12898:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:12898:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:12898:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:12898:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:12898:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:12898:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:12898:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:12896:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_new_Geometry(int, VALUE*, VALUE)’:
ogr.cpp:13254:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:13254:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:13254:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:13254:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:13252:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_Geometry_export_to_wkt(int, VALUE*, VALUE)’:
ogr.cpp:13374:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_Geometry_export_to_wkb(int, VALUE*, VALUE)’:
ogr.cpp:13434:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:13434:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:13480:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp:13432:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_Geometry_add_point(int, VALUE*, VALUE)’:
ogr.cpp:13708:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:13708:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:13708:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:13708:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:13706:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_Geometry_add_geometry_directly(int, VALUE*, VALUE)’:
ogr.cpp:13887:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_Geometry_add_geometry(int, VALUE*, VALUE)’:
ogr.cpp:13963:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_Geometry_get_x(int, VALUE*, VALUE)’:
ogr.cpp:14368:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:14368:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:14366:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_Geometry_get_y(int, VALUE*, VALUE)’:
ogr.cpp:14434:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:14434:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:14432:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_Geometry_get_z(int, VALUE*, VALUE)’:
ogr.cpp:14500:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:14500:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:14498:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_Geometry_set_point(int, VALUE*, VALUE)’:
ogr.cpp:14788:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:14788:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:14788:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:14788:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:14788:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:14786:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_Geometry_set_point_2d(int, VALUE*, VALUE)’:
ogr.cpp:14872:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:14872:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:14872:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:14872:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:14870:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_Geometry_buffer(int, VALUE*, VALUE)’:
ogr.cpp:15288:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:15288:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:15288:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:15286:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_Geometry_transform_to(int, VALUE*, VALUE)’:
ogr.cpp:16772:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_Geometry_transform(int, VALUE*, VALUE)’:
ogr.cpp:16848:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_set_generate_db2_v72_byte_order(int, VALUE*, VALUE)’:
ogr.cpp:17680:56: error: format not a string literal and no format arguments [-Werror=format-security]
       rb_raise(rb_eRuntimeError, OGRErrMessages(result));
                                                        ^
ogr.cpp: In function ‘VALUE _wrap_open(int, VALUE*, VALUE)’:
ogr.cpp:17909:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:17909:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:17907:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
ogr.cpp: In function ‘VALUE _wrap_open_shared(int, VALUE*, VALUE)’:
ogr.cpp:17978:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
   };
   ^
ogr.cpp:17978:3: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
ogr.cpp:17976:9: warning: unused variable ‘kwnames’ [-Wunused-variable]
   char *kwnames[] = {
         ^
cc1plus: some warnings being treated as errors
make: *** [ogr.o] Error 1
```

**Comment by zhm** [comment]
Sorry this took so long to get fixed. I made a change in 53852746941256091a62be673dce75723725c15b that makes it work on Ubuntu 14.04 without needing to patch the sources or the ruby config. A proper fix should be done upstream in GDAL (and possible it is already). Until I get time to update the binding code from upstream, this fix will have to do.

**Comment by timwaters** [comment]
hmm, so I got an error installing this
```
extconf.rb:16:in `<main>': undefined method `<<' for nil:NilClass (NoMethodError)
```

with ruby-1.9.3-p547

I note this comment in this file which may hint at it: 
https://github.com/Hanmac/rwx/blob/master/ext/extconf.rb#L45

**Comment by zhm** [comment]
Can you try version 0.0.7?

**Comment by zhm** [comment]
This should be resolved now with 1.0.0.

**Comment by timwaters** [comment]
:+1:

**Comment by dolorierp** [comment]
Thank you
